ALTER TABLE data_annotation_task
    DROP CONSTRAINT ck_data_annotation_task_status;

UPDATE data_annotation_task
SET status = CASE status
    WHEN 'OPEN' THEN 'PENDING'
    WHEN 'COMPLETED' THEN 'SUBMITTED'
    ELSE status
END;

ALTER TABLE data_annotation_task
    ALTER COLUMN status TYPE VARCHAR(24),
    ALTER COLUMN status SET DEFAULT 'PENDING',
    ADD COLUMN project_id BIGINT,
    ADD COLUMN annotator_id BIGINT,
    ADD COLUMN reviewer_id BIGINT,
    ADD COLUMN rejection_reason VARCHAR(1000),
    ADD COLUMN deleted_at TIMESTAMPTZ;

UPDATE data_annotation_task task
SET project_id = source.project_id,
    annotator_id = task.creator_id
FROM (
    SELECT task_id, min(project_id) AS project_id
    FROM data_dataset
    WHERE task_id IS NOT NULL
    GROUP BY task_id
) source
WHERE source.task_id = task.id;

ALTER TABLE data_annotation_task
    ADD CONSTRAINT uk_annotation_task_name UNIQUE (name),
    ADD CONSTRAINT fk_annotation_task_project FOREIGN KEY (project_id)
        REFERENCES basic_project (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_annotation_task_annotator FOREIGN KEY (annotator_id)
        REFERENCES sys_user (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_annotation_task_reviewer FOREIGN KEY (reviewer_id)
        REFERENCES sys_user (id) ON DELETE RESTRICT,
    ADD CONSTRAINT ck_annotation_task_status CHECK (
        status IN ('PENDING', 'WORKING', 'REVIEW_PENDING', 'REJECTED', 'APPROVED', 'SUBMITTED')
    ),
    ADD CONSTRAINT ck_annotation_task_rejection_reason CHECK (
        rejection_reason IS NULL OR char_length(rejection_reason) <= 1000
    );

CREATE INDEX idx_annotation_task_status_created
    ON data_annotation_task (status, created_at DESC, id DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_annotation_task_project
    ON data_annotation_task (project_id, created_at DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_annotation_task_people
    ON data_annotation_task (annotator_id, reviewer_id, creator_id)
    WHERE deleted_at IS NULL;

CREATE TABLE data_annotation_task_dataset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    dataset_id BIGINT NOT NULL,
    annotation_description TEXT,
    check_result VARCHAR(16),
    rejection_reason VARCHAR(1000),
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    unassigned_at TIMESTAMPTZ,
    CONSTRAINT fk_annotation_dataset_task FOREIGN KEY (task_id)
        REFERENCES data_annotation_task (id) ON DELETE CASCADE,
    CONSTRAINT fk_annotation_dataset_data FOREIGN KEY (dataset_id)
        REFERENCES data_dataset (id) ON DELETE RESTRICT,
    CONSTRAINT ck_annotation_dataset_result CHECK (
        check_result IS NULL OR check_result IN ('VALID', 'INVALID')
    ),
    CONSTRAINT ck_annotation_dataset_reason CHECK (
        rejection_reason IS NULL OR char_length(rejection_reason) <= 1000
    )
);

CREATE UNIQUE INDEX uk_annotation_dataset_active
    ON data_annotation_task_dataset (dataset_id)
    WHERE unassigned_at IS NULL;
CREATE INDEX idx_annotation_dataset_task
    ON data_annotation_task_dataset (task_id, assigned_at, id)
    WHERE unassigned_at IS NULL;

INSERT INTO sys_menu_permission
    (id, parent_id, type, name, code, sort_order, visible, enabled)
VALUES
    (1441, 1440, 'BUTTON', '执行标注', 'data:annotate:task:execute', 10, FALSE, TRUE),
    (1442, 1440, 'BUTTON', '审核标注', 'data:annotate:task:review', 20, FALSE, TRUE),
    (1443, 1440, 'BUTTON', '管理标注任务', 'data:annotate:task:manage', 30, FALSE, TRUE)
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    type = EXCLUDED.type,
    name = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order,
    visible = EXCLUDED.visible,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE r.code IN ('SUPER_ADMIN', 'MANAGER', 'AUDITOR', 'ANNOTATOR')
  AND p.code IN ('data:view', 'data:annotate:task:view')
ON CONFLICT DO NOTHING;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE (r.code IN ('SUPER_ADMIN', 'MANAGER')
       AND p.code IN ('data:annotate:task:execute', 'data:annotate:task:review',
                      'data:annotate:task:manage'))
   OR (r.code = 'AUDITOR' AND p.code = 'data:annotate:task:review')
   OR (r.code = 'ANNOTATOR' AND p.code = 'data:annotate:task:execute')
ON CONFLICT DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('sys_menu_permission', 'id'),
    (SELECT MAX(id) FROM sys_menu_permission),
    TRUE
);
