CREATE TABLE data_collection_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    project_id BIGINT NOT NULL,
    target_count INTEGER NOT NULL DEFAULT 1,
    average_duration_seconds INTEGER NOT NULL DEFAULT 60,
    notes VARCHAR(2000),
    initial_scene VARCHAR(2000),
    remote_operation_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    created_by BIGINT NOT NULL,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_collection_task_name UNIQUE (name),
    CONSTRAINT fk_collection_task_project FOREIGN KEY (project_id)
        REFERENCES basic_project (id) ON DELETE RESTRICT,
    CONSTRAINT fk_collection_task_creator FOREIGN KEY (created_by)
        REFERENCES sys_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_collection_task_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_collection_task_target_count CHECK (target_count >= 1),
    CONSTRAINT ck_collection_task_average_duration CHECK (average_duration_seconds >= 1),
    CONSTRAINT ck_collection_task_status CHECK (
        status IN ('PENDING', 'WORKING', 'REVIEW_PENDING', 'REJECTED', 'APPROVED', 'SUBMITTED')
    )
);

CREATE INDEX idx_collection_task_project_status
    ON data_collection_task (project_id, status, updated_at DESC, id DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_collection_task_creator
    ON data_collection_task (created_by, id)
    WHERE deleted_at IS NULL;

CREATE TABLE data_collection_task_assignee (
    task_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (task_id, user_id),
    CONSTRAINT fk_collection_assignee_task FOREIGN KEY (task_id)
        REFERENCES data_collection_task (id) ON DELETE CASCADE,
    CONSTRAINT fk_collection_assignee_user FOREIGN KEY (user_id)
        REFERENCES sys_user (id) ON DELETE RESTRICT
);

CREATE INDEX idx_collection_assignee_user
    ON data_collection_task_assignee (user_id, task_id);

CREATE TABLE data_collection_task_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    sequence_no INTEGER NOT NULL,
    action_name VARCHAR(200),
    object_name VARCHAR(200),
    target_name VARCHAR(200),
    notes VARCHAR(500),
    CONSTRAINT fk_collection_step_task FOREIGN KEY (task_id)
        REFERENCES data_collection_task (id) ON DELETE CASCADE,
    CONSTRAINT uk_collection_step_sequence UNIQUE (task_id, sequence_no),
    CONSTRAINT ck_collection_step_sequence CHECK (sequence_no >= 1),
    CONSTRAINT ck_collection_step_content CHECK (
        NULLIF(btrim(action_name), '') IS NOT NULL
        OR NULLIF(btrim(notes), '') IS NOT NULL
    )
);

CREATE TABLE data_collection_task_dataset (
    task_id BIGINT NOT NULL,
    dataset_id BIGINT NOT NULL,
    linked_by BIGINT,
    linked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (task_id, dataset_id),
    CONSTRAINT fk_collection_dataset_task FOREIGN KEY (task_id)
        REFERENCES data_collection_task (id) ON DELETE CASCADE,
    CONSTRAINT fk_collection_dataset_data FOREIGN KEY (dataset_id)
        REFERENCES data_dataset (id) ON DELETE CASCADE,
    CONSTRAINT fk_collection_dataset_linker FOREIGN KEY (linked_by)
        REFERENCES sys_user (id) ON DELETE SET NULL
);

CREATE INDEX idx_collection_dataset_recent
    ON data_collection_task_dataset (task_id, linked_at DESC, dataset_id DESC);

INSERT INTO sys_menu_permission
    (id, parent_id, type, name, code, sort_order, visible, enabled)
VALUES
    (1431, 1430, 'BUTTON', '管理采集任务', 'data:collect:task:manage', 10, FALSE, TRUE),
    (1432, 1430, 'BUTTON', '审核采集任务', 'data:collect:task:review', 20, FALSE, TRUE),
    (1433, 1430, 'BUTTON', '提交采集任务', 'data:collect:task:submit', 30, FALSE, TRUE),
    (1434, 1430, 'BUTTON', '解除采集数据关联', 'data:collect:task:unlink-data', 40, FALSE, TRUE),
    (1435, 1430, 'BUTTON', '管理全部采集任务', 'data:collect:task:admin', 50, FALSE, TRUE)
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    type = EXCLUDED.type,
    name = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order,
    visible = EXCLUDED.visible,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE r.code IN ('SUPER_ADMIN', 'MANAGER', 'COLLECTOR', 'ANNOTATOR', 'AUDITOR')
  AND p.code IN ('data:view', 'data:collect:task:view', 'data:collect:task:manage')
ON CONFLICT DO NOTHING;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE r.code IN ('SUPER_ADMIN', 'MANAGER', 'AUDITOR')
  AND p.code IN ('data:collect:task:review', 'data:collect:task:unlink-data')
ON CONFLICT DO NOTHING;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE r.code IN ('SUPER_ADMIN', 'MANAGER')
  AND p.code = 'data:collect:task:submit'
ON CONFLICT DO NOTHING;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE r.code = 'SUPER_ADMIN'
  AND p.code = 'data:collect:task:admin'
ON CONFLICT DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('sys_menu_permission', 'id'),
    (SELECT MAX(id) FROM sys_menu_permission),
    TRUE
);
