CREATE TABLE ai_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacturer VARCHAR(100) NOT NULL,
    name VARCHAR(160) NOT NULL,
    access_address VARCHAR(500) NOT NULL,
    model_url VARCHAR(1000) NOT NULL,
    model_type VARCHAR(32) NOT NULL,
    access_key_ciphertext TEXT,
    secret_key_ciphertext TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_test_status VARCHAR(16) NOT NULL DEFAULT 'NEVER',
    last_test_message VARCHAR(500),
    last_test_latency_ms BIGINT,
    last_tested_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_model_manufacturer_name UNIQUE (manufacturer, name),
    CONSTRAINT ck_ai_model_manufacturer_not_blank CHECK (btrim(manufacturer) <> ''),
    CONSTRAINT ck_ai_model_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_ai_model_access_address_not_blank CHECK (btrim(access_address) <> ''),
    CONSTRAINT ck_ai_model_url_not_blank CHECK (btrim(model_url) <> ''),
    CONSTRAINT ck_ai_model_type CHECK (
        model_type IN ('CHAT', 'EMBEDDING', 'MULTIMODAL', 'RERANK', 'IMAGE', 'AUDIO')
    ),
    CONSTRAINT ck_ai_model_test_status CHECK (
        last_test_status IN ('NEVER', 'SUCCESS', 'FAILED')
    ),
    CONSTRAINT ck_ai_model_test_latency CHECK (
        last_test_latency_ms IS NULL OR last_test_latency_ms >= 0
    )
);

CREATE INDEX idx_ai_model_type_enabled
    ON ai_model (model_type, enabled, updated_at DESC);

INSERT INTO sys_menu_permission
    (id, parent_id, type, name, code, sort_order, visible, enabled)
VALUES
    (1661, 1660, 'BUTTON', '新增模型', 'basic:model:create', 10, FALSE, TRUE),
    (1662, 1660, 'BUTTON', '编辑模型', 'basic:model:update', 20, FALSE, TRUE),
    (1663, 1660, 'BUTTON', '删除模型', 'basic:model:delete', 30, FALSE, TRUE),
    (1664, 1660, 'BUTTON', '测试模型', 'basic:model:test', 40, FALSE, TRUE)
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    type = EXCLUDED.type,
    name = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order,
    visible = EXCLUDED.visible,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE r.code = 'SUPER_ADMIN'
  AND p.code IN (
      'basic:model:view',
      'basic:model:create',
      'basic:model:update',
      'basic:model:delete',
      'basic:model:test'
  )
ON CONFLICT DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('sys_menu_permission', 'id'),
    (SELECT MAX(id) FROM sys_menu_permission),
    TRUE
);
