CREATE TABLE sys_department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(64) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_department_code UNIQUE (code),
    CONSTRAINT fk_department_parent FOREIGN KEY (parent_id)
        REFERENCES sys_department (id) ON DELETE RESTRICT,
    CONSTRAINT ck_department_not_self CHECK (parent_id IS NULL OR parent_id <> id),
    CONSTRAINT ck_department_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_department_parent_sort
    ON sys_department (parent_id, sort_order, id);

CREATE TABLE sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    email VARCHAR(254),
    phone VARCHAR(32),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    password_changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_username UNIQUE (username),
    CONSTRAINT fk_user_department FOREIGN KEY (department_id)
        REFERENCES sys_department (id) ON DELETE RESTRICT,
    CONSTRAINT ck_user_username_normalized CHECK (username = lower(username)),
    CONSTRAINT ck_user_username_not_blank CHECK (btrim(username) <> ''),
    CONSTRAINT ck_user_display_name_not_blank CHECK (btrim(display_name) <> '')
);

CREATE UNIQUE INDEX uk_user_email_normalized
    ON sys_user (lower(email))
    WHERE email IS NOT NULL;
CREATE INDEX idx_user_department ON sys_user (department_id);
CREATE INDEX idx_user_enabled_created ON sys_user (enabled, created_at DESC);

CREATE TABLE sys_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(64) NOT NULL,
    description VARCHAR(500),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    built_in BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_role_name UNIQUE (name),
    CONSTRAINT uk_role_code UNIQUE (code),
    CONSTRAINT ck_role_code_normalized CHECK (code = upper(code)),
    CONSTRAINT ck_role_code_not_blank CHECK (btrim(code) <> '')
);

CREATE INDEX idx_role_enabled ON sys_role (enabled);

CREATE TABLE sys_menu_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    type VARCHAR(16) NOT NULL,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(100),
    path VARCHAR(255),
    component VARCHAR(255),
    icon VARCHAR(100),
    sort_order INTEGER NOT NULL DEFAULT 0,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_menu_permission_code UNIQUE (code),
    CONSTRAINT fk_menu_permission_parent FOREIGN KEY (parent_id)
        REFERENCES sys_menu_permission (id) ON DELETE RESTRICT,
    CONSTRAINT ck_menu_permission_type CHECK (type IN ('MENU', 'BUTTON')),
    CONSTRAINT ck_menu_permission_not_self CHECK (parent_id IS NULL OR parent_id <> id),
    CONSTRAINT ck_menu_permission_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_button_permission_code CHECK (type <> 'BUTTON' OR code IS NOT NULL),
    CONSTRAINT ck_menu_permission_name_not_blank CHECK (btrim(name) <> '')
);

CREATE INDEX idx_menu_permission_parent_sort
    ON sys_menu_permission (parent_id, sort_order, id);
CREATE INDEX idx_menu_permission_type_enabled
    ON sys_menu_permission (type, enabled);

CREATE TABLE sys_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by BIGINT,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id)
        REFERENCES sys_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id)
        REFERENCES sys_role (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_role_assigner FOREIGN KEY (assigned_by)
        REFERENCES sys_user (id) ON DELETE SET NULL
);

CREATE INDEX idx_user_role_role ON sys_user_role (role_id, user_id);

CREATE TABLE sys_role_permission (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id)
        REFERENCES sys_role (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id)
        REFERENCES sys_menu_permission (id) ON DELETE CASCADE
);

CREATE INDEX idx_role_permission_permission
    ON sys_role_permission (permission_id, role_id);

CREATE TABLE auth_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(128) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ,
    ip_address VARCHAR(45),
    user_agent VARCHAR(512),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_auth_session_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_auth_session_user FOREIGN KEY (user_id)
        REFERENCES sys_user (id) ON DELETE CASCADE,
    CONSTRAINT ck_auth_session_expiry CHECK (expires_at > created_at),
    CONSTRAINT ck_auth_session_revocation CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX idx_auth_session_active_user
    ON auth_session (user_id, expires_at)
    WHERE revoked_at IS NULL;
CREATE INDEX idx_auth_session_expiry ON auth_session (expires_at);

CREATE TABLE file_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket_name VARCHAR(63) NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(255),
    size_bytes BIGINT NOT NULL,
    etag VARCHAR(128),
    uploader_id BIGINT,
    status VARCHAR(16) NOT NULL DEFAULT 'READY',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_file_object UNIQUE (bucket_name, object_key),
    CONSTRAINT fk_file_uploader FOREIGN KEY (uploader_id)
        REFERENCES sys_user (id) ON DELETE SET NULL,
    CONSTRAINT ck_file_size CHECK (size_bytes >= 0),
    CONSTRAINT ck_file_status CHECK (status IN ('PENDING', 'READY', 'DELETING', 'FAILED')),
    CONSTRAINT ck_file_bucket_not_blank CHECK (btrim(bucket_name) <> ''),
    CONSTRAINT ck_file_object_key_not_blank CHECK (btrim(object_key) <> ''),
    CONSTRAINT ck_file_original_name_not_blank CHECK (btrim(original_name) <> '')
);

CREATE INDEX idx_file_uploader_created
    ON file_metadata (uploader_id, created_at DESC);
CREATE INDEX idx_file_status_created
    ON file_metadata (status, created_at DESC);

CREATE TABLE operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id BIGINT,
    operator_name VARCHAR(64),
    module VARCHAR(64) NOT NULL,
    action VARCHAR(64) NOT NULL,
    target_type VARCHAR(64),
    target_id VARCHAR(128),
    result VARCHAR(16) NOT NULL,
    error_summary VARCHAR(500),
    ip_address VARCHAR(45),
    user_agent VARCHAR(512),
    request_id VARCHAR(128),
    details TEXT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    duration_ms BIGINT,
    CONSTRAINT fk_operation_log_operator FOREIGN KEY (operator_id)
        REFERENCES sys_user (id) ON DELETE SET NULL,
    CONSTRAINT ck_operation_log_result CHECK (result IN ('SUCCESS', 'FAILURE')),
    CONSTRAINT ck_operation_log_duration CHECK (duration_ms IS NULL OR duration_ms >= 0),
    CONSTRAINT ck_operation_log_module_not_blank CHECK (btrim(module) <> ''),
    CONSTRAINT ck_operation_log_action_not_blank CHECK (btrim(action) <> '')
);

CREATE INDEX idx_operation_log_occurred ON operation_log (occurred_at DESC);
CREATE INDEX idx_operation_log_operator_occurred
    ON operation_log (operator_id, occurred_at DESC);
CREATE INDEX idx_operation_log_module_result_occurred
    ON operation_log (module, result, occurred_at DESC);
CREATE INDEX idx_operation_log_request_id ON operation_log (request_id);
