CREATE TABLE cloud_storage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_key VARCHAR(64) NOT NULL,
    name VARCHAR(120) NOT NULL,
    provider VARCHAR(24) NOT NULL,
    endpoint VARCHAR(500) NOT NULL,
    region VARCHAR(100),
    bucket VARCHAR(255) NOT NULL,
    access_key_ciphertext TEXT NOT NULL,
    secret_key_ciphertext TEXT NOT NULL,
    default_storage BOOLEAN NOT NULL DEFAULT FALSE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(16) NOT NULL DEFAULT 'NEVER',
    last_check_message VARCHAR(500),
    last_check_latency_ms BIGINT,
    usage_bytes BIGINT NOT NULL DEFAULT 0,
    object_count BIGINT NOT NULL DEFAULT 0,
    last_checked_at TIMESTAMPTZ,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cloud_storage_key UNIQUE (storage_key),
    CONSTRAINT uk_cloud_storage_name UNIQUE (name),
    CONSTRAINT fk_cloud_storage_creator FOREIGN KEY (created_by)
        REFERENCES sys_user (id) ON DELETE SET NULL,
    CONSTRAINT ck_cloud_storage_key_not_blank CHECK (btrim(storage_key) <> ''),
    CONSTRAINT ck_cloud_storage_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_cloud_storage_endpoint_not_blank CHECK (btrim(endpoint) <> ''),
    CONSTRAINT ck_cloud_storage_bucket_not_blank CHECK (btrim(bucket) <> ''),
    CONSTRAINT ck_cloud_storage_provider CHECK (
        provider IN ('TENCENT_COS', 'ALIYUN_OSS', 'HUAWEI_OBS', 'AWS_S3', 'AZURE_BLOB', 'CLOUDFLARE_R2', 'MINIO')
    ),
    CONSTRAINT ck_cloud_storage_status CHECK (
        status IN ('NEVER', 'AVAILABLE', 'UNAVAILABLE')
    ),
    CONSTRAINT ck_cloud_storage_latency CHECK (
        last_check_latency_ms IS NULL OR last_check_latency_ms >= 0
    ),
    CONSTRAINT ck_cloud_storage_usage CHECK (
        usage_bytes >= 0 AND object_count >= 0
    )
);

CREATE UNIQUE INDEX uk_cloud_storage_default
    ON cloud_storage (default_storage)
    WHERE default_storage = TRUE;

CREATE INDEX idx_cloud_storage_enabled_provider
    ON cloud_storage (enabled, provider, updated_at DESC);

INSERT INTO sys_menu_permission
    (id, parent_id, type, name, code, sort_order, visible, enabled)
VALUES
    (1641, 1640, 'BUTTON', '新增存储', 'basic:storage:create', 10, FALSE, TRUE),
    (1642, 1640, 'BUTTON', '编辑存储', 'basic:storage:update', 20, FALSE, TRUE),
    (1643, 1640, 'BUTTON', '删除存储', 'basic:storage:delete', 30, FALSE, TRUE),
    (1644, 1640, 'BUTTON', '测试连接', 'basic:storage:test', 40, FALSE, TRUE),
    (1645, 1640, 'BUTTON', '设置默认存储', 'basic:storage:default', 50, FALSE, TRUE)
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    type = EXCLUDED.type,
    name = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order,
    visible = EXCLUDED.visible,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE r.code = 'SUPER_ADMIN'
  AND p.code IN (
      'basic:storage:view',
      'basic:storage:create',
      'basic:storage:update',
      'basic:storage:delete',
      'basic:storage:test',
      'basic:storage:default'
  )
ON CONFLICT DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('sys_menu_permission', 'id'),
    (SELECT MAX(id) FROM sys_menu_permission),
    TRUE
);
