CREATE TABLE ai_agent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    system_prompt TEXT NOT NULL,
    model_id BIGINT NOT NULL,
    temperature NUMERIC(3, 2) NOT NULL DEFAULT 0.70,
    max_tokens INTEGER NOT NULL DEFAULT 2048,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_agent_name UNIQUE (name),
    CONSTRAINT fk_ai_agent_model FOREIGN KEY (model_id)
        REFERENCES ai_model (id) ON DELETE RESTRICT,
    CONSTRAINT ck_ai_agent_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_ai_agent_prompt_not_blank CHECK (btrim(system_prompt) <> ''),
    CONSTRAINT ck_ai_agent_temperature CHECK (temperature >= 0 AND temperature <= 2),
    CONSTRAINT ck_ai_agent_max_tokens CHECK (max_tokens BETWEEN 1 AND 32768)
);

CREATE INDEX idx_ai_agent_model_enabled
    ON ai_agent (model_id, enabled, updated_at DESC);

UPDATE sys_menu_permission
SET sort_order = 80,
    updated_at = CURRENT_TIMESTAMP
WHERE code = 'basic:operations:view';

INSERT INTO sys_menu_permission
    (id, parent_id, type, name, code, path, component, icon, sort_order, visible, enabled)
VALUES
    (1680, 1600, 'MENU', 'Agent 管理', 'basic:agent:view',
        '/basic/agents', 'basic/agent/index', 'agent', 70, TRUE, TRUE),
    (1681, 1680, 'BUTTON', '新增 Agent', 'basic:agent:create',
        NULL, NULL, NULL, 10, FALSE, TRUE),
    (1682, 1680, 'BUTTON', '编辑 Agent', 'basic:agent:update',
        NULL, NULL, NULL, 20, FALSE, TRUE),
    (1683, 1680, 'BUTTON', '删除 Agent', 'basic:agent:delete',
        NULL, NULL, NULL, 30, FALSE, TRUE),
    (1684, 1680, 'BUTTON', '调试 Agent', 'basic:agent:debug',
        NULL, NULL, NULL, 40, FALSE, TRUE)
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    type = EXCLUDED.type,
    name = EXCLUDED.name,
    path = EXCLUDED.path,
    component = EXCLUDED.component,
    icon = EXCLUDED.icon,
    sort_order = EXCLUDED.sort_order,
    visible = EXCLUDED.visible,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE r.code = 'SUPER_ADMIN'
  AND p.code IN (
      'basic:agent:view',
      'basic:agent:create',
      'basic:agent:update',
      'basic:agent:delete',
      'basic:agent:debug'
  )
ON CONFLICT DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('sys_menu_permission', 'id'),
    (SELECT MAX(id) FROM sys_menu_permission),
    TRUE
);
