CREATE TABLE data_dictionary_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dictionary_type VARCHAR(24) NOT NULL,
    scope VARCHAR(16) NOT NULL,
    project_id BIGINT,
    english_text VARCHAR(300) NOT NULL,
    chinese_text VARCHAR(300) NOT NULL,
    japanese_text VARCHAR(300),
    use_count BIGINT NOT NULL DEFAULT 0,
    creator_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dictionary_project FOREIGN KEY (project_id)
        REFERENCES basic_project (id) ON DELETE RESTRICT,
    CONSTRAINT fk_dictionary_creator FOREIGN KEY (creator_id)
        REFERENCES sys_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_dictionary_type CHECK (
        dictionary_type IN (
            'SKILL', 'OBJECT', 'TARGET', 'ADVERBIAL',
            'INVALID', 'TAG', 'TAG_CATEGORY'
        )
    ),
    CONSTRAINT ck_dictionary_scope CHECK (
        scope IN ('GLOBAL', 'SHARED', 'PROJECT')
    ),
    CONSTRAINT ck_dictionary_project_scope CHECK (
        (scope = 'PROJECT' AND project_id IS NOT NULL)
        OR (scope <> 'PROJECT' AND project_id IS NULL)
    ),
    CONSTRAINT ck_dictionary_english_not_blank CHECK (btrim(english_text) <> ''),
    CONSTRAINT ck_dictionary_chinese_not_blank CHECK (btrim(chinese_text) <> ''),
    CONSTRAINT ck_dictionary_use_count CHECK (use_count >= 0)
);

CREATE UNIQUE INDEX uk_dictionary_global_english
    ON data_dictionary_entry (dictionary_type, lower(english_text))
    WHERE scope = 'GLOBAL';

CREATE UNIQUE INDEX uk_dictionary_creator_english
    ON data_dictionary_entry (dictionary_type, lower(english_text), creator_id)
    WHERE scope <> 'GLOBAL';

CREATE INDEX idx_dictionary_type_scope_created
    ON data_dictionary_entry (dictionary_type, scope, created_at DESC, id DESC);
CREATE INDEX idx_dictionary_project_type
    ON data_dictionary_entry (project_id, dictionary_type, id)
    WHERE project_id IS NOT NULL;

INSERT INTO sys_menu_permission
    (id, parent_id, type, name, code, sort_order, visible, enabled)
VALUES
    (1461, 1460, 'BUTTON', '管理字典', 'data:dict:manage', 10, FALSE, TRUE),
    (1462, 1460, 'BUTTON', '管理全局字典', 'data:dict:global', 20, FALSE, TRUE)
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    type = EXCLUDED.type,
    name = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order,
    visible = EXCLUDED.visible,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE r.code = 'SUPER_ADMIN'
  AND p.code IN ('data:dict:view', 'data:dict:manage', 'data:dict:global')
ON CONFLICT DO NOTHING;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE r.code IN ('MANAGER', 'ANNOTATOR', 'AUDITOR')
  AND p.code IN ('data:view', 'data:dict:view', 'data:dict:manage')
ON CONFLICT DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('sys_menu_permission', 'id'),
    (SELECT MAX(id) FROM sys_menu_permission),
    TRUE
);
