CREATE TABLE basic_robot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    icon_url VARCHAR(1000) NOT NULL,
    title_zh VARCHAR(255),
    title_en VARCHAR(255),
    robot_type VARCHAR(32) NOT NULL DEFAULT 'OTHER',
    action_mapping_support VARCHAR(16) NOT NULL DEFAULT 'UNSUPPORTED',
    description TEXT,
    company VARCHAR(100),
    introduction_url VARCHAR(1000),
    built_in BOOLEAN NOT NULL DEFAULT FALSE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_basic_robot_name UNIQUE (name),
    CONSTRAINT ck_basic_robot_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_basic_robot_icon_not_blank CHECK (btrim(icon_url) <> ''),
    CONSTRAINT ck_basic_robot_type CHECK (
        robot_type IN (
            'HUMANOID', 'MOBILE_MANIPULATOR', 'DESKTOP_ARM', 'MOBILE_BASE',
            'QUADRUPED', 'INDUSTRIAL_ARM', 'OTHER'
        )
    ),
    CONSTRAINT ck_basic_robot_action_mapping CHECK (
        action_mapping_support IN ('SUPPORTED', 'COMING_SOON', 'UNSUPPORTED')
    ),
    CONSTRAINT ck_basic_robot_deleted CHECK (deleted_at IS NULL OR deleted = TRUE)
);

CREATE INDEX idx_basic_robot_catalog
    ON basic_robot (deleted, robot_type, name);

INSERT INTO basic_robot
    (name, icon_url, title_zh, title_en, robot_type, action_mapping_support, company, built_in)
VALUES
    ('unitree-g1', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=clean%20studio%20product%20photo%20of%20a%20humanoid%20robot%2C%20white%20background%2C%20full%20body%2C%20realistic&image_size=square', '宇树 G1', 'Unitree G1', 'HUMANOID', 'SUPPORTED', 'Unitree', TRUE),
    ('unitree-h1', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=clean%20studio%20product%20photo%20of%20a%20humanoid%20robot%2C%20white%20background%2C%20full%20body%2C%20realistic&image_size=square', '宇树 H1', 'Unitree H1', 'HUMANOID', 'COMING_SOON', 'Unitree', TRUE),
    ('galbot-g1', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=clean%20studio%20product%20photo%20of%20a%20service%20humanoid%20robot%2C%20white%20background%2C%20realistic&image_size=square', '银河通用 G1', 'Galbot G1', 'HUMANOID', 'COMING_SOON', 'Galbot', TRUE),
    ('fourier-gr1', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=clean%20studio%20product%20photo%20of%20a%20humanoid%20robot%2C%20white%20background%2C%20realistic&image_size=square', '傅利叶 GR-1', 'Fourier GR-1', 'HUMANOID', 'COMING_SOON', 'Fourier Intelligence', TRUE),
    ('agibot-x1', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=clean%20studio%20product%20photo%20of%20a%20compact%20humanoid%20robot%2C%20white%20background%2C%20realistic&image_size=square', '智元 X1', 'AgiBot X1', 'HUMANOID', 'COMING_SOON', 'AgiBot', TRUE),
    ('aloha-mobile', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=mobile%20dual%20arm%20research%20robot%2C%20clean%20studio%20product%20photo%2C%20white%20background&image_size=square', 'Mobile ALOHA', 'Mobile ALOHA', 'MOBILE_MANIPULATOR', 'SUPPORTED', 'Stanford', TRUE),
    ('agilex-cobot-magic', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=mobile%20dual%20arm%20robot%20with%20wheeled%20base%2C%20clean%20product%20photo%2C%20white%20background&image_size=square', 'Cobot Magic', 'Cobot Magic', 'MOBILE_MANIPULATOR', 'SUPPORTED', 'AgileX', TRUE),
    ('galaxea-r1', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=mobile%20manipulator%20robot%20with%20two%20arms%2C%20studio%20product%20photo%2C%20white%20background&image_size=square', '星海图 R1', 'Galaxea R1', 'MOBILE_MANIPULATOR', 'COMING_SOON', 'Galaxea AI', TRUE),
    ('stretch-3', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=slender%20mobile%20manipulator%20robot%20with%20telescoping%20arm%2C%20studio%20photo%2C%20white%20background&image_size=square', 'Stretch 3', 'Stretch 3', 'MOBILE_MANIPULATOR', 'SUPPORTED', 'Hello Robot', TRUE),
    ('aloha', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=tabletop%20dual%20robot%20arm%20research%20platform%2C%20studio%20product%20photo%2C%20white%20background&image_size=square', 'ALOHA 双臂', 'ALOHA Bimanual', 'DESKTOP_ARM', 'SUPPORTED', 'Stanford', TRUE),
    ('so100', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=compact%20six-axis%20desktop%20robot%20arm%2C%20studio%20product%20photo%2C%20white%20background&image_size=square', 'SO-100 机械臂', 'SO-100 Arm', 'DESKTOP_ARM', 'SUPPORTED', 'TheRobotStudio', TRUE),
    ('so101', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=compact%20six-axis%20desktop%20robot%20arm%2C%20studio%20product%20photo%2C%20white%20background&image_size=square', 'SO-101 机械臂', 'SO-101 Arm', 'DESKTOP_ARM', 'SUPPORTED', 'TheRobotStudio', TRUE),
    ('agilex-piper', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=compact%20desktop%20robotic%20arm%20with%20gripper%2C%20studio%20product%20photo%2C%20white%20background&image_size=square', '松灵 Piper', 'AgileX Piper', 'DESKTOP_ARM', 'SUPPORTED', 'AgileX', TRUE),
    ('xarm6', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=six-axis%20desktop%20robotic%20arm%2C%20studio%20product%20photo%2C%20white%20background&image_size=square', 'xArm 6', 'xArm 6', 'DESKTOP_ARM', 'SUPPORTED', 'UFACTORY', TRUE),
    ('lite6', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=compact%20lightweight%20desktop%20robotic%20arm%2C%20studio%20product%20photo%2C%20white%20background&image_size=square', 'Lite 6', 'Lite 6', 'DESKTOP_ARM', 'COMING_SOON', 'UFACTORY', TRUE),
    ('lekiwi', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=small%20three-wheel%20mobile%20robot%20with%20robotic%20arm%2C%20studio%20product%20photo%2C%20white%20background&image_size=square', 'LeKiwi', 'LeKiwi', 'MOBILE_BASE', 'SUPPORTED', 'Hugging Face', TRUE),
    ('turtlebot4', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=compact%20circular%20mobile%20robot%20base%20with%20lidar%2C%20studio%20photo%2C%20white%20background&image_size=square', 'TurtleBot 4', 'TurtleBot 4', 'MOBILE_BASE', 'COMING_SOON', 'Clearpath Robotics', TRUE),
    ('unitree-go2', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=quadruped%20robot%20dog%2C%20clean%20studio%20product%20photo%2C%20white%20background%2C%20realistic&image_size=square', '宇树 Go2', 'Unitree Go2', 'QUADRUPED', 'SUPPORTED', 'Unitree', TRUE),
    ('unitree-b2', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=industrial%20quadruped%20robot%2C%20clean%20studio%20product%20photo%2C%20white%20background%2C%20realistic&image_size=square', '宇树 B2', 'Unitree B2', 'QUADRUPED', 'COMING_SOON', 'Unitree', TRUE),
    ('franka-panda', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=collaborative%20industrial%20robot%20arm%20with%20gripper%2C%20studio%20product%20photo%2C%20white%20background&image_size=square', 'Franka Panda', 'Franka Panda', 'INDUSTRIAL_ARM', 'SUPPORTED', 'Franka Robotics', TRUE),
    ('franka-fr3', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=modern%20collaborative%20industrial%20robot%20arm%2C%20studio%20product%20photo%2C%20white%20background&image_size=square', 'Franka FR3', 'Franka FR3', 'INDUSTRIAL_ARM', 'COMING_SOON', 'Franka Robotics', TRUE),
    ('ur5e', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=six-axis%20collaborative%20industrial%20robot%20arm%2C%20studio%20product%20photo%2C%20white%20background&image_size=square', 'UR5e', 'UR5e', 'INDUSTRIAL_ARM', 'COMING_SOON', 'Universal Robots', TRUE),
    ('kinova-gen3', 'https://copilot-cn.bytedance.net/api/ide/v1/text_to_image?prompt=seven-axis%20collaborative%20robot%20arm%2C%20studio%20product%20photo%2C%20white%20background&image_size=square', 'Kinova Gen3', 'Kinova Gen3', 'INDUSTRIAL_ARM', 'COMING_SOON', 'Kinova', TRUE);

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE r.code IN ('SUPER_ADMIN', 'MANAGER')
  AND p.code IN ('basic:view', 'basic:robot:view')
ON CONFLICT DO NOTHING;
