CREATE TABLE data_export_quota (
    user_id BIGINT PRIMARY KEY,
    quota_limit INTEGER NOT NULL DEFAULT 1000,
    updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_data_export_quota_user FOREIGN KEY (user_id)
        REFERENCES sys_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_data_export_quota_updater FOREIGN KEY (updated_by)
        REFERENCES sys_user (id) ON DELETE SET NULL,
    CONSTRAINT ck_data_export_quota_limit CHECK (quota_limit >= 0)
);

CREATE TABLE data_export_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    format VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    progress INTEGER NOT NULL DEFAULT 0,
    processed_count INTEGER NOT NULL DEFAULT 0,
    dataset_count INTEGER NOT NULL,
    config_json TEXT NOT NULL DEFAULT '{}',
    file_name VARCHAR(512),
    object_key VARCHAR(1024),
    content_type VARCHAR(128),
    file_size BIGINT,
    error_message VARCHAR(2000),
    creator_id BIGINT NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_data_export_task_creator FOREIGN KEY (creator_id)
        REFERENCES sys_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_data_export_task_name CHECK (btrim(name) <> ''),
    CONSTRAINT ck_data_export_task_format CHECK (
        format IN (
            'LEROBOT', 'HDF5', 'MCAP', 'JSON', 'CSV',
            'YOLO', 'COCO', 'VOC', 'TIME_ALIGNMENT',
            'DROPPED_FRAME', 'MCAP_CHUNK'
        )
    ),
    CONSTRAINT ck_data_export_task_status CHECK (
        status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')
    ),
    CONSTRAINT ck_data_export_task_progress CHECK (progress BETWEEN 0 AND 100),
    CONSTRAINT ck_data_export_task_counts CHECK (
        dataset_count > 0 AND processed_count >= 0
        AND processed_count <= dataset_count
    ),
    CONSTRAINT ck_data_export_task_file_size CHECK (
        file_size IS NULL OR file_size >= 0
    )
);

CREATE INDEX idx_data_export_task_creator
    ON data_export_task (creator_id, created_at DESC, id DESC);
CREATE INDEX idx_data_export_task_queue
    ON data_export_task (status, created_at, id)
    WHERE status IN ('PENDING', 'PROCESSING');

CREATE TABLE data_export_task_dataset (
    task_id BIGINT NOT NULL,
    dataset_id BIGINT NOT NULL,
    sequence_no INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (task_id, dataset_id),
    CONSTRAINT fk_data_export_rel_task FOREIGN KEY (task_id)
        REFERENCES data_export_task (id) ON DELETE CASCADE,
    CONSTRAINT fk_data_export_rel_dataset FOREIGN KEY (dataset_id)
        REFERENCES data_dataset (id) ON DELETE RESTRICT,
    CONSTRAINT uk_data_export_rel_sequence UNIQUE (task_id, sequence_no),
    CONSTRAINT ck_data_export_rel_sequence CHECK (sequence_no > 0)
);

CREATE INDEX idx_data_export_rel_dataset
    ON data_export_task_dataset (dataset_id, task_id);

INSERT INTO sys_menu_permission
    (id, parent_id, type, name, code, sort_order, visible, enabled)
VALUES
    (1491, 1490, 'BUTTON', '创建导出任务', 'data:export:create', 10, FALSE, TRUE),
    (1492, 1490, 'BUTTON', '下载导出文件', 'data:export:download', 20, FALSE, TRUE),
    (1493, 1490, 'BUTTON', '管理导出配额', 'data:export:quota', 30, FALSE, TRUE)
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    type = EXCLUDED.type,
    name = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order,
    visible = EXCLUDED.visible,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE (r.code IN ('SUPER_ADMIN', 'MANAGER')
       AND p.code IN ('data:export:create', 'data:export:download'))
   OR (r.code = 'SUPER_ADMIN' AND p.code = 'data:export:quota')
ON CONFLICT DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('sys_menu_permission', 'id'),
    (SELECT MAX(id) FROM sys_menu_permission),
    TRUE
);
