CREATE TABLE data_qc_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(500),
    scope VARCHAR(16) NOT NULL,
    project_id BIGINT,
    dataset_pattern VARCHAR(200) NOT NULL DEFAULT '*',
    algorithm_code VARCHAR(64) NOT NULL DEFAULT 'MCAP_STRUCTURAL',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    priority INTEGER NOT NULL DEFAULT 100,
    assertions_json TEXT NOT NULL DEFAULT '[]',
    creator_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_qc_rule_project FOREIGN KEY (project_id)
        REFERENCES basic_project (id) ON DELETE CASCADE,
    CONSTRAINT fk_qc_rule_creator FOREIGN KEY (creator_id)
        REFERENCES sys_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_qc_rule_name CHECK (btrim(name) <> ''),
    CONSTRAINT ck_qc_rule_scope CHECK (scope IN ('GLOBAL', 'PROJECT')),
    CONSTRAINT ck_qc_rule_project_scope CHECK (
        (scope = 'GLOBAL' AND project_id IS NULL)
        OR (scope = 'PROJECT' AND project_id IS NOT NULL)
    ),
    CONSTRAINT ck_qc_rule_pattern CHECK (btrim(dataset_pattern) <> ''),
    CONSTRAINT ck_qc_rule_algorithm CHECK (algorithm_code = 'MCAP_STRUCTURAL'),
    CONSTRAINT ck_qc_rule_assertions_json CHECK (assertions_json::jsonb IS NOT NULL)
);

CREATE INDEX idx_qc_rule_scope_priority
    ON data_qc_rule (scope, project_id, enabled, priority, id);

CREATE TABLE data_qc_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id BIGINT NOT NULL,
    dataset_id BIGINT NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'QUEUED',
    progress INTEGER NOT NULL DEFAULT 0,
    passed BOOLEAN,
    report_json TEXT,
    result_json TEXT,
    error_message VARCHAR(2000),
    trigger_type VARCHAR(16) NOT NULL DEFAULT 'MANUAL',
    override_pass BOOLEAN,
    override_reason VARCHAR(500),
    override_by BIGINT,
    override_at TIMESTAMPTZ,
    created_by BIGINT NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_qc_execution_rule FOREIGN KEY (rule_id)
        REFERENCES data_qc_rule (id) ON DELETE CASCADE,
    CONSTRAINT fk_qc_execution_dataset FOREIGN KEY (dataset_id)
        REFERENCES data_dataset (id) ON DELETE CASCADE,
    CONSTRAINT fk_qc_execution_override_user FOREIGN KEY (override_by)
        REFERENCES sys_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_qc_execution_creator FOREIGN KEY (created_by)
        REFERENCES sys_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_qc_execution_status CHECK (
        status IN ('QUEUED', 'RUNNING', 'PASSED', 'FAILED', 'ERROR', 'CANCELLED')
    ),
    CONSTRAINT ck_qc_execution_progress CHECK (progress BETWEEN 0 AND 100),
    CONSTRAINT ck_qc_execution_trigger CHECK (
        trigger_type IN ('AUTO', 'MANUAL', 'BACKFILL')
    ),
    CONSTRAINT ck_qc_execution_report_json CHECK (
        report_json IS NULL OR report_json::jsonb IS NOT NULL
    ),
    CONSTRAINT ck_qc_execution_result_json CHECK (
        result_json IS NULL OR result_json::jsonb IS NOT NULL
    ),
    CONSTRAINT ck_qc_execution_override CHECK (
        (override_pass IS NULL AND override_reason IS NULL
         AND override_by IS NULL AND override_at IS NULL)
        OR
        (override_pass IS NOT NULL AND override_reason IS NOT NULL
         AND override_by IS NOT NULL AND override_at IS NOT NULL)
    )
);

CREATE INDEX idx_qc_execution_dataset_created
    ON data_qc_execution (dataset_id, created_at DESC, id DESC);
CREATE INDEX idx_qc_execution_rule_created
    ON data_qc_execution (rule_id, created_at DESC, id DESC);
CREATE INDEX idx_qc_execution_status_created
    ON data_qc_execution (status, created_at, id);
CREATE UNIQUE INDEX uk_qc_execution_active
    ON data_qc_execution (rule_id, dataset_id)
    WHERE status IN ('QUEUED', 'RUNNING');

INSERT INTO sys_menu_permission
    (id, parent_id, type, name, code, sort_order, visible, enabled)
VALUES
    (1451, 1450, 'BUTTON', '执行质检', 'data:qc:execute', 10, FALSE, TRUE),
    (1452, 1450, 'BUTTON', '管理质检规则', 'data:qc:rule:manage', 20, FALSE, TRUE),
    (1453, 1450, 'BUTTON', '管理全局质检规则', 'data:qc:rule:global', 30, FALSE, TRUE),
    (1454, 1450, 'BUTTON', '覆盖质检结论', 'data:qc:override', 40, FALSE, TRUE)
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    type = EXCLUDED.type,
    name = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order,
    visible = EXCLUDED.visible,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE (r.code = 'SUPER_ADMIN'
       AND p.code IN (
           'data:qc:view', 'data:qc:execute', 'data:qc:rule:manage',
           'data:qc:rule:global', 'data:qc:override'
       ))
   OR (r.code = 'MANAGER'
       AND p.code IN (
           'data:view', 'data:qc:view', 'data:qc:execute',
           'data:qc:rule:manage', 'data:qc:override'
       ))
   OR (r.code = 'COLLECTOR'
       AND p.code IN ('data:view', 'data:qc:view', 'data:qc:execute'))
ON CONFLICT DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('sys_menu_permission', 'id'),
    (SELECT MAX(id) FROM sys_menu_permission),
    TRUE
);
