CREATE TABLE basic_device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id UUID NOT NULL,
    agent_token UUID NOT NULL,
    device_code VARCHAR(128) NOT NULL,
    remark VARCHAR(1000),
    robot_id BIGINT,
    project_id BIGINT,
    created_by BIGINT NOT NULL,
    collection_task_id BIGINT,
    last_report_at TIMESTAMPTZ,
    hostname VARCHAR(255),
    operating_system VARCHAR(255),
    platform VARCHAR(255),
    kernel_version VARCHAR(255),
    ip_addresses VARCHAR(1000),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_basic_device_agent_id UNIQUE (agent_id),
    CONSTRAINT uk_basic_device_agent_token UNIQUE (agent_token),
    CONSTRAINT uk_basic_device_code UNIQUE (device_code),
    CONSTRAINT fk_basic_device_robot FOREIGN KEY (robot_id)
        REFERENCES basic_robot (id) ON DELETE SET NULL,
    CONSTRAINT fk_basic_device_project FOREIGN KEY (project_id)
        REFERENCES basic_project (id) ON DELETE SET NULL,
    CONSTRAINT fk_basic_device_creator FOREIGN KEY (created_by)
        REFERENCES sys_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_basic_device_collection_task FOREIGN KEY (collection_task_id)
        REFERENCES data_collection_task (id) ON DELETE SET NULL,
    CONSTRAINT ck_basic_device_code CHECK (
        device_code ~ '^[A-Za-z0-9_-]{3,128}$'
    ),
    CONSTRAINT ck_basic_device_deleted CHECK (deleted_at IS NULL OR deleted = TRUE)
);

CREATE INDEX idx_basic_device_project
    ON basic_device (project_id, updated_at DESC)
    WHERE deleted = FALSE;
CREATE INDEX idx_basic_device_last_report
    ON basic_device (last_report_at DESC)
    WHERE deleted = FALSE;

CREATE TABLE basic_device_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    cpu_usage NUMERIC(5, 2) NOT NULL,
    memory_usage NUMERIC(5, 2) NOT NULL,
    disk_usage NUMERIC(5, 2) NOT NULL,
    cpu_temperature NUMERIC(6, 2),
    memory_used_bytes BIGINT,
    disk_available_bytes BIGINT,
    active_tcp_connections INTEGER NOT NULL DEFAULT 0,
    uptime_seconds BIGINT NOT NULL DEFAULT 0,
    reported_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_device_report_device FOREIGN KEY (device_id)
        REFERENCES basic_device (id) ON DELETE CASCADE,
    CONSTRAINT ck_device_report_percentages CHECK (
        cpu_usage BETWEEN 0 AND 100
        AND memory_usage BETWEEN 0 AND 100
        AND disk_usage BETWEEN 0 AND 100
    ),
    CONSTRAINT ck_device_report_values CHECK (
        COALESCE(memory_used_bytes, 0) >= 0
        AND COALESCE(disk_available_bytes, 0) >= 0
        AND active_tcp_connections >= 0
        AND uptime_seconds >= 0
    )
);

CREATE INDEX idx_device_report_history
    ON basic_device_report (device_id, reported_at DESC);

INSERT INTO sys_menu_permission
    (id, parent_id, type, name, code, sort_order, visible, enabled)
VALUES
    (1631, 1630, 'BUTTON', '管理设备', 'basic:device:manage', 10, FALSE, TRUE),
    (1632, 1630, 'BUTTON', '查看遥操作', 'basic:device:remote:view', 20, FALSE, TRUE),
    (1633, 1630, 'BUTTON', '管理遥操作', 'basic:device:remote:manage', 30, FALSE, TRUE)
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    type = EXCLUDED.type,
    name = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order,
    visible = EXCLUDED.visible,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE r.code IN ('SUPER_ADMIN', 'MANAGER', 'COLLECTOR')
  AND p.code IN ('basic:view', 'basic:device:view', 'basic:device:remote:view')
ON CONFLICT DO NOTHING;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE r.code IN ('SUPER_ADMIN', 'MANAGER')
  AND p.code IN ('basic:device:manage', 'basic:device:remote:manage')
ON CONFLICT DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('sys_menu_permission', 'id'),
    (SELECT MAX(id) FROM sys_menu_permission),
    TRUE
);
