CREATE TABLE monitor_metric_sample (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    database_latency_ms BIGINT NOT NULL,
    redis_latency_ms BIGINT,
    queue_backlog INTEGER NOT NULL,
    cpu_usage_percent NUMERIC(5, 2) NOT NULL,
    memory_usage_percent NUMERIC(5, 2) NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_monitor_metric_database_latency CHECK (database_latency_ms >= 0),
    CONSTRAINT ck_monitor_metric_redis_latency CHECK (
        redis_latency_ms IS NULL OR redis_latency_ms >= 0
    ),
    CONSTRAINT ck_monitor_metric_queue_backlog CHECK (queue_backlog >= 0),
    CONSTRAINT ck_monitor_metric_cpu CHECK (cpu_usage_percent BETWEEN 0 AND 100),
    CONSTRAINT ck_monitor_metric_memory CHECK (memory_usage_percent BETWEEN 0 AND 100)
);

CREATE INDEX idx_monitor_metric_collected
    ON monitor_metric_sample (collected_at DESC);

CREATE TABLE request_access_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    username VARCHAR(64),
    method VARCHAR(10) NOT NULL,
    request_path VARCHAR(1024) NOT NULL,
    status_code INTEGER NOT NULL,
    duration_ms BIGINT NOT NULL,
    ip_address VARCHAR(45),
    user_agent VARCHAR(512),
    request_id VARCHAR(128),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_access_log_user FOREIGN KEY (user_id)
        REFERENCES sys_user (id) ON DELETE SET NULL,
    CONSTRAINT ck_access_log_status CHECK (status_code BETWEEN 100 AND 599),
    CONSTRAINT ck_access_log_duration CHECK (duration_ms >= 0)
);

CREATE INDEX idx_access_log_occurred
    ON request_access_log (occurred_at DESC);
CREATE INDEX idx_access_log_user_occurred
    ON request_access_log (user_id, occurred_at DESC);
CREATE INDEX idx_access_log_status_occurred
    ON request_access_log (status_code, occurred_at DESC);

CREATE TABLE monitor_queue_state (
    queue_name VARCHAR(64) PRIMARY KEY,
    paused BOOLEAN NOT NULL DEFAULT FALSE,
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_monitor_queue_state_updater FOREIGN KEY (updated_by)
        REFERENCES sys_user (id) ON DELETE SET NULL
);

INSERT INTO monitor_queue_state (queue_name, paused)
VALUES ('EXPORT', FALSE);

ALTER TABLE data_export_task
    DROP CONSTRAINT ck_data_export_task_status;
ALTER TABLE data_export_task
    ADD CONSTRAINT ck_data_export_task_status CHECK (
        status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELED')
    );

INSERT INTO sys_menu_permission
    (id, parent_id, type, name, code, sort_order, visible, enabled)
VALUES
    (1671, 1670, 'BUTTON', '采集监控指标', 'basic:operations:collect', 10, FALSE, TRUE),
    (1672, 1670, 'BUTTON', '管理后台队列', 'basic:operations:queue', 20, FALSE, TRUE)
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    type = EXCLUDED.type,
    name = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order,
    visible = EXCLUDED.visible,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE r.code = 'SUPER_ADMIN'
  AND p.code IN ('basic:operations:collect', 'basic:operations:queue')
ON CONFLICT DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('sys_menu_permission', 'id'),
    (SELECT MAX(id) FROM sys_menu_permission),
    TRUE
);
