CREATE TABLE workflow_match_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(500),
    scope VARCHAR(16) NOT NULL,
    project_id BIGINT,
    priority INTEGER NOT NULL DEFAULT 100,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    logic_operator VARCHAR(8) NOT NULL DEFAULT 'AND',
    conditions_json TEXT NOT NULL DEFAULT '[]',
    creator_id BIGINT NOT NULL,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_workflow_match_project FOREIGN KEY (project_id)
        REFERENCES basic_project (id) ON DELETE CASCADE,
    CONSTRAINT fk_workflow_match_creator FOREIGN KEY (creator_id)
        REFERENCES sys_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_workflow_match_name CHECK (btrim(name) <> ''),
    CONSTRAINT ck_workflow_match_scope CHECK (scope IN ('GLOBAL', 'PROJECT')),
    CONSTRAINT ck_workflow_match_project_scope CHECK (
        (scope = 'GLOBAL' AND project_id IS NULL)
        OR (scope = 'PROJECT' AND project_id IS NOT NULL)
    ),
    CONSTRAINT ck_workflow_match_logic CHECK (logic_operator IN ('AND', 'OR')),
    CONSTRAINT ck_workflow_match_conditions CHECK (
        conditions_json::jsonb IS NOT NULL
        AND jsonb_typeof(conditions_json::jsonb) = 'array'
    )
);

CREATE INDEX idx_workflow_match_active
    ON workflow_match_rule (scope, project_id, enabled, priority, id)
    WHERE deleted_at IS NULL;

CREATE TABLE workflow_action_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(500),
    scope VARCHAR(16) NOT NULL,
    project_id BIGINT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    steps_json TEXT NOT NULL DEFAULT '[]',
    creator_id BIGINT NOT NULL,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_workflow_action_project FOREIGN KEY (project_id)
        REFERENCES basic_project (id) ON DELETE CASCADE,
    CONSTRAINT fk_workflow_action_creator FOREIGN KEY (creator_id)
        REFERENCES sys_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_workflow_action_name CHECK (btrim(name) <> ''),
    CONSTRAINT ck_workflow_action_scope CHECK (scope IN ('GLOBAL', 'PROJECT')),
    CONSTRAINT ck_workflow_action_project_scope CHECK (
        (scope = 'GLOBAL' AND project_id IS NULL)
        OR (scope = 'PROJECT' AND project_id IS NOT NULL)
    ),
    CONSTRAINT ck_workflow_action_steps CHECK (
        steps_json::jsonb IS NOT NULL
        AND jsonb_typeof(steps_json::jsonb) = 'array'
    )
);

CREATE INDEX idx_workflow_action_active
    ON workflow_action_rule (scope, project_id, enabled, id)
    WHERE deleted_at IS NULL;

CREATE TABLE workflow_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(500),
    scope VARCHAR(16) NOT NULL,
    project_id BIGINT,
    priority INTEGER NOT NULL DEFAULT 100,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    match_rule_id BIGINT NOT NULL,
    action_rule_id BIGINT NOT NULL,
    creator_id BIGINT NOT NULL,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_workflow_definition_project FOREIGN KEY (project_id)
        REFERENCES basic_project (id) ON DELETE CASCADE,
    CONSTRAINT fk_workflow_definition_match FOREIGN KEY (match_rule_id)
        REFERENCES workflow_match_rule (id) ON DELETE RESTRICT,
    CONSTRAINT fk_workflow_definition_action FOREIGN KEY (action_rule_id)
        REFERENCES workflow_action_rule (id) ON DELETE RESTRICT,
    CONSTRAINT fk_workflow_definition_creator FOREIGN KEY (creator_id)
        REFERENCES sys_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_workflow_definition_name CHECK (btrim(name) <> ''),
    CONSTRAINT ck_workflow_definition_scope CHECK (scope IN ('GLOBAL', 'PROJECT')),
    CONSTRAINT ck_workflow_definition_project_scope CHECK (
        (scope = 'GLOBAL' AND project_id IS NULL)
        OR (scope = 'PROJECT' AND project_id IS NOT NULL)
    )
);

CREATE INDEX idx_workflow_definition_active
    ON workflow_definition (scope, project_id, enabled, priority, id)
    WHERE deleted_at IS NULL;

CREATE TABLE workflow_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT NOT NULL,
    dataset_id BIGINT NOT NULL,
    stage VARCHAR(32) NOT NULL DEFAULT 'MATCHING',
    status VARCHAR(16) NOT NULL DEFAULT 'QUEUED',
    progress INTEGER NOT NULL DEFAULT 0,
    trigger_type VARCHAR(16) NOT NULL DEFAULT 'MANUAL',
    steps_snapshot_json TEXT NOT NULL DEFAULT '[]',
    error_message VARCHAR(2000),
    created_by BIGINT NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_workflow_run_definition FOREIGN KEY (workflow_id)
        REFERENCES workflow_definition (id) ON DELETE RESTRICT,
    CONSTRAINT fk_workflow_run_dataset FOREIGN KEY (dataset_id)
        REFERENCES data_dataset (id) ON DELETE RESTRICT,
    CONSTRAINT fk_workflow_run_creator FOREIGN KEY (created_by)
        REFERENCES sys_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_workflow_run_stage CHECK (
        stage IN ('MATCHING', 'NORMALIZING', 'PROCESSING', 'QUALITY', 'ANNOTATION', 'DELIVERY')
    ),
    CONSTRAINT ck_workflow_run_status CHECK (
        status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')
    ),
    CONSTRAINT ck_workflow_run_progress CHECK (progress BETWEEN 0 AND 100),
    CONSTRAINT ck_workflow_run_trigger CHECK (trigger_type IN ('AUTO', 'MANUAL', 'TEST')),
    CONSTRAINT ck_workflow_run_steps CHECK (
        steps_snapshot_json::jsonb IS NOT NULL
        AND jsonb_typeof(steps_snapshot_json::jsonb) = 'array'
    )
);

CREATE INDEX idx_workflow_run_recent
    ON workflow_run (status, created_at DESC, id DESC);
CREATE INDEX idx_workflow_run_dataset
    ON workflow_run (dataset_id, created_at DESC, id DESC);

UPDATE sys_menu_permission
SET path = '/workflows/overview',
    component = 'workflow/index',
    icon = 'workflow',
    updated_at = CURRENT_TIMESTAMP
WHERE code = 'basic:workflow:view';

INSERT INTO sys_menu_permission
    (id, parent_id, type, name, code, sort_order, visible, enabled)
VALUES
    (1651, 1650, 'BUTTON', '管理流程', 'basic:workflow:manage', 10, FALSE, TRUE),
    (1652, 1650, 'BUTTON', '测试流程', 'basic:workflow:test', 20, FALSE, TRUE),
    (1653, 1650, 'BUTTON', '管理全局流程', 'basic:workflow:global', 30, FALSE, TRUE)
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    name = EXCLUDED.name,
    enabled = TRUE,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE (r.code = 'SUPER_ADMIN'
       AND p.code IN (
           'basic:workflow:view', 'basic:workflow:manage',
           'basic:workflow:test', 'basic:workflow:global'
       ))
   OR (r.code = 'MANAGER'
       AND p.code IN ('basic:view', 'basic:workflow:view', 'basic:workflow:manage',
                      'basic:workflow:test'))
ON CONFLICT DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('sys_menu_permission', 'id'),
    (SELECT MAX(id) FROM sys_menu_permission),
    TRUE
);
