CREATE TABLE data_skill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_key VARCHAR(128) NOT NULL UNIQUE,
    name_zh VARCHAR(128) NOT NULL,
    name_en VARCHAR(128) NOT NULL,
    description VARCHAR(1000),
    category VARCHAR(24) NOT NULL DEFAULT 'BASIC',
    difficulty VARCHAR(24) NOT NULL DEFAULT 'BEGINNER',
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    current_version VARCHAR(32) NOT NULL DEFAULT '1.0.0',
    usage_scene VARCHAR(200),
    tags TEXT[] NOT NULL DEFAULT '{}',
    is_template BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_data_skill_key CHECK (btrim(skill_key) <> ''),
    CONSTRAINT ck_data_skill_category CHECK (
        category IN ('BASIC', 'COMPOSITE', 'PROFESSIONAL')
    ),
    CONSTRAINT ck_data_skill_difficulty CHECK (
        difficulty IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT')
    ),
    CONSTRAINT ck_data_skill_status CHECK (
        status IN ('DRAFT', 'PUBLISHED', 'DEPRECATED')
    )
);

CREATE TABLE data_skill_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id BIGINT NOT NULL,
    version VARCHAR(32) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    change_summary VARCHAR(500),
    definition_json TEXT NOT NULL DEFAULT '{}',
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_skill_version_skill FOREIGN KEY (skill_id)
        REFERENCES data_skill (id) ON DELETE CASCADE,
    CONSTRAINT uk_skill_version UNIQUE (skill_id, version),
    CONSTRAINT ck_skill_version_status CHECK (
        status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')
    ),
    CONSTRAINT ck_skill_version_definition CHECK (definition_json::jsonb IS NOT NULL)
);

CREATE TABLE data_skill_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_skill_id BIGINT NOT NULL,
    target_skill_id BIGINT NOT NULL,
    relation_type VARCHAR(24) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_skill_relation_source FOREIGN KEY (source_skill_id)
        REFERENCES data_skill (id) ON DELETE CASCADE,
    CONSTRAINT fk_skill_relation_target FOREIGN KEY (target_skill_id)
        REFERENCES data_skill (id) ON DELETE CASCADE,
    CONSTRAINT uk_skill_relation UNIQUE (
        source_skill_id, target_skill_id, relation_type
    ),
    CONSTRAINT ck_skill_relation_self CHECK (source_skill_id <> target_skill_id),
    CONSTRAINT ck_skill_relation_type CHECK (
        relation_type IN ('PARENT', 'DEPENDENCY', 'ALTERNATIVE', 'COMPOSITION')
    )
);

WITH skill_sources AS (
    SELECT lower(btrim(skill_name)) AS skill_key,
           COALESCE(NULLIF(btrim(skill_name_zh), ''), btrim(skill_name)) AS name_zh,
           btrim(skill_name) AS name_en,
           1 AS source_priority,
           id
    FROM data_annotation
    WHERE NULLIF(btrim(skill_name), '') IS NOT NULL
    UNION ALL
    SELECT lower(btrim(english_text)),
           btrim(chinese_text),
           btrim(english_text),
           2,
           id
    FROM data_dictionary_entry
    WHERE dictionary_type = 'SKILL'
)
INSERT INTO data_skill (skill_key, name_zh, name_en)
SELECT DISTINCT ON (skill_key)
       skill_key, name_zh, name_en
FROM skill_sources
ORDER BY skill_key, source_priority, id;

INSERT INTO data_skill_version (
    skill_id, version, status, change_summary, definition_json, published_at
)
SELECT id, current_version, 'PUBLISHED', 'Initial catalog version', '{}', CURRENT_TIMESTAMP
FROM data_skill;

CREATE OR REPLACE FUNCTION sync_annotation_skill_catalog()
RETURNS TRIGGER AS $$
BEGIN
    IF NULLIF(btrim(NEW.skill_name), '') IS NOT NULL THEN
        INSERT INTO data_skill (skill_key, name_zh, name_en)
        VALUES (
            lower(btrim(NEW.skill_name)),
            COALESCE(NULLIF(btrim(NEW.skill_name_zh), ''), btrim(NEW.skill_name)),
            btrim(NEW.skill_name)
        )
        ON CONFLICT (skill_key) DO UPDATE
        SET name_zh = COALESCE(
                NULLIF(btrim(EXCLUDED.name_zh), ''),
                data_skill.name_zh
            ),
            updated_at = CURRENT_TIMESTAMP;

        INSERT INTO data_skill_version (
            skill_id, version, status, change_summary, definition_json, published_at
        )
        SELECT id, '1.0.0', 'PUBLISHED', 'Initial catalog version', '{}', CURRENT_TIMESTAMP
        FROM data_skill
        WHERE skill_key = lower(btrim(NEW.skill_name))
        ON CONFLICT (skill_id, version) DO NOTHING;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_annotation_skill_catalog
AFTER INSERT OR UPDATE OF skill_name, skill_name_zh
ON data_annotation
FOR EACH ROW
EXECUTE FUNCTION sync_annotation_skill_catalog();

CREATE INDEX idx_data_skill_classification
    ON data_skill (category, difficulty, status, updated_at DESC);
CREATE INDEX idx_data_skill_tags
    ON data_skill USING GIN (tags);
CREATE INDEX idx_skill_version_skill_created
    ON data_skill_version (skill_id, created_at DESC);
CREATE INDEX idx_skill_relation_source
    ON data_skill_relation (source_skill_id, relation_type);
