CREATE TABLE mqtt_connection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    client_id VARCHAR(128) NOT NULL,
    broker_url VARCHAR(500) NOT NULL,
    username_ciphertext TEXT,
    password_ciphertext TEXT,
    tls_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    clean_session BOOLEAN NOT NULL DEFAULT TRUE,
    keep_alive_seconds INTEGER NOT NULL DEFAULT 60,
    connection_timeout_seconds INTEGER NOT NULL DEFAULT 10,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(16) NOT NULL DEFAULT 'NEVER',
    last_check_message VARCHAR(500),
    last_check_latency_ms BIGINT,
    last_checked_at TIMESTAMPTZ,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mqtt_connection_name UNIQUE (name),
    CONSTRAINT uk_mqtt_connection_client_id UNIQUE (client_id),
    CONSTRAINT fk_mqtt_connection_creator FOREIGN KEY (created_by)
        REFERENCES sys_user (id) ON DELETE SET NULL,
    CONSTRAINT ck_mqtt_connection_name CHECK (btrim(name) <> ''),
    CONSTRAINT ck_mqtt_connection_client_id CHECK (btrim(client_id) <> ''),
    CONSTRAINT ck_mqtt_connection_broker CHECK (
        broker_url ~ '^(tcp|ssl|ws|wss)://'
    ),
    CONSTRAINT ck_mqtt_connection_keep_alive CHECK (
        keep_alive_seconds BETWEEN 5 AND 3600
    ),
    CONSTRAINT ck_mqtt_connection_timeout CHECK (
        connection_timeout_seconds BETWEEN 1 AND 120
    ),
    CONSTRAINT ck_mqtt_connection_status CHECK (
        status IN ('NEVER', 'AVAILABLE', 'UNAVAILABLE')
    ),
    CONSTRAINT ck_mqtt_connection_latency CHECK (
        last_check_latency_ms IS NULL OR last_check_latency_ms >= 0
    )
);

CREATE TABLE mqtt_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL,
    topic_filter VARCHAR(500) NOT NULL,
    qos SMALLINT NOT NULL DEFAULT 0,
    description VARCHAR(500),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mqtt_subscription_topic UNIQUE (connection_id, topic_filter),
    CONSTRAINT fk_mqtt_subscription_connection FOREIGN KEY (connection_id)
        REFERENCES mqtt_connection (id) ON DELETE CASCADE,
    CONSTRAINT fk_mqtt_subscription_creator FOREIGN KEY (created_by)
        REFERENCES sys_user (id) ON DELETE SET NULL,
    CONSTRAINT ck_mqtt_subscription_topic CHECK (btrim(topic_filter) <> ''),
    CONSTRAINT ck_mqtt_subscription_qos CHECK (qos BETWEEN 0 AND 2)
);

CREATE INDEX idx_mqtt_connection_enabled
    ON mqtt_connection (enabled, status, updated_at DESC);
CREATE INDEX idx_mqtt_subscription_connection
    ON mqtt_subscription (connection_id, enabled, updated_at DESC);

INSERT INTO sys_menu_permission
    (id, parent_id, type, name, code, path, component, icon, sort_order, visible, enabled)
VALUES
    (1690, 1600, 'MENU', '消息管理', 'basic:mqtt:view',
     '/basic/mqtt', 'basic/mqtt/index', 'message', 75, TRUE, TRUE),
    (1691, 1690, 'BUTTON', '管理 MQTT 配置', 'basic:mqtt:manage',
     NULL, NULL, NULL, 10, FALSE, TRUE),
    (1692, 1690, 'BUTTON', '测试 MQTT 连接', 'basic:mqtt:test',
     NULL, NULL, NULL, 20, FALSE, TRUE)
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    type = EXCLUDED.type,
    name = EXCLUDED.name,
    path = EXCLUDED.path,
    component = EXCLUDED.component,
    icon = EXCLUDED.icon,
    sort_order = EXCLUDED.sort_order,
    visible = EXCLUDED.visible,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE r.code = 'SUPER_ADMIN'
  AND p.code IN ('basic:mqtt:view', 'basic:mqtt:manage', 'basic:mqtt:test')
ON CONFLICT DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('sys_menu_permission', 'id'),
    (SELECT MAX(id) FROM sys_menu_permission),
    TRUE
);
