CREATE TABLE basic_project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(1000),
    project_type VARCHAR(16) NOT NULL,
    access_level VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PLANNING',
    storage_provider VARCHAR(32) NOT NULL DEFAULT 'MINIO',
    storage_quota_bytes BIGINT NOT NULL,
    start_date DATE,
    end_date DATE,
    annotation_guideline TEXT,
    quality_threshold NUMERIC(5, 2) NOT NULL DEFAULT 90.00,
    review_mode VARCHAR(24) NOT NULL DEFAULT 'SINGLE_REVIEW',
    notification_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_basic_project_code UNIQUE (code),
    CONSTRAINT fk_basic_project_owner FOREIGN KEY (owner_id)
        REFERENCES sys_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_basic_project_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT ck_basic_project_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_basic_project_type
        CHECK (project_type IN ('PERSONAL', 'TEAM', 'SHARED')),
    CONSTRAINT ck_basic_project_access
        CHECK (access_level IN ('PUBLIC', 'PRIVATE', 'RESTRICTED')),
    CONSTRAINT ck_basic_project_status
        CHECK (status IN ('PLANNING', 'ACTIVE', 'SUSPENDED', 'COMPLETED', 'ARCHIVED')),
    CONSTRAINT ck_basic_project_quota CHECK (storage_quota_bytes > 0),
    CONSTRAINT ck_basic_project_dates
        CHECK (start_date IS NULL OR end_date IS NULL OR start_date <= end_date),
    CONSTRAINT ck_basic_project_quality
        CHECK (quality_threshold >= 0 AND quality_threshold <= 100),
    CONSTRAINT ck_basic_project_review
        CHECK (review_mode IN ('NONE', 'SINGLE_REVIEW', 'DOUBLE_REVIEW'))
);

CREATE INDEX idx_basic_project_status_updated
    ON basic_project (status, updated_at DESC, id DESC);
CREATE INDEX idx_basic_project_owner ON basic_project (owner_id, id);

CREATE TABLE basic_project_member (
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(24) NOT NULL,
    data_access_level VARCHAR(16) NOT NULL DEFAULT 'READ_WRITE',
    valid_from TIMESTAMPTZ,
    valid_until TIMESTAMPTZ,
    assigned_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (project_id, user_id),
    CONSTRAINT fk_basic_project_member_project FOREIGN KEY (project_id)
        REFERENCES basic_project (id) ON DELETE CASCADE,
    CONSTRAINT fk_basic_project_member_user FOREIGN KEY (user_id)
        REFERENCES sys_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_basic_project_member_assigner FOREIGN KEY (assigned_by)
        REFERENCES sys_user (id) ON DELETE SET NULL,
    CONSTRAINT ck_basic_project_member_role
        CHECK (role IN ('PROJECT_ADMIN', 'PROJECT_MANAGER', 'ANNOTATOR', 'REVIEWER', 'OBSERVER')),
    CONSTRAINT ck_basic_project_member_access
        CHECK (data_access_level IN ('READ_ONLY', 'READ_WRITE', 'FULL')),
    CONSTRAINT ck_basic_project_member_validity
        CHECK (valid_from IS NULL OR valid_until IS NULL OR valid_from < valid_until)
);

CREATE INDEX idx_basic_project_member_user
    ON basic_project_member (user_id, project_id);
CREATE INDEX idx_basic_project_member_validity
    ON basic_project_member (project_id, valid_from, valid_until);

INSERT INTO sys_menu_permission
    (id, parent_id, type, name, code, sort_order, visible, enabled)
VALUES
    (1611, 1610, 'BUTTON', '新增项目', 'basic:project:create', 10, FALSE, TRUE),
    (1612, 1610, 'BUTTON', '编辑项目', 'basic:project:update', 20, FALSE, TRUE),
    (1613, 1610, 'BUTTON', '变更项目状态', 'basic:project:change-status', 30, FALSE, TRUE),
    (1614, 1610, 'BUTTON', '删除项目', 'basic:project:delete', 40, FALSE, TRUE),
    (1615, 1610, 'BUTTON', '查看项目成员', 'basic:project:member:view', 50, FALSE, TRUE),
    (1616, 1610, 'BUTTON', '管理项目成员', 'basic:project:member:manage', 60, FALSE, TRUE)
ON CONFLICT (code) DO UPDATE
SET parent_id = EXCLUDED.parent_id,
    type = EXCLUDED.type,
    name = EXCLUDED.name,
    sort_order = EXCLUDED.sort_order,
    visible = EXCLUDED.visible,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE r.code = 'SUPER_ADMIN'
  AND p.code IN (
      'basic:project:create',
      'basic:project:update',
      'basic:project:change-status',
      'basic:project:delete',
      'basic:project:member:view',
      'basic:project:member:manage'
  )
ON CONFLICT DO NOTHING;

INSERT INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM sys_role r
CROSS JOIN sys_menu_permission p
WHERE r.code IN ('MANAGER', 'COLLECTOR', 'ANNOTATOR', 'AUDITOR')
  AND p.code IN ('basic:view', 'basic:project:view', 'basic:project:member:view')
ON CONFLICT DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('sys_menu_permission', 'id'),
    (SELECT MAX(id) FROM sys_menu_permission),
    TRUE
);
