-- 菜单：数据管理（sort_order = 15）

-- 子菜单：数据管理
-- 合并 V9 数据管理字段与 V10 上传字段，供当前两组代码路径共享。
CREATE TABLE data_dataset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    file_id BIGINT,
    thumbnail_object_key VARCHAR(1024),
    data_type VARCHAR(32) NOT NULL,
    size_bytes BIGINT NOT NULL,
    duration_seconds NUMERIC(12, 3),
    annotation_status VARCHAR(16) NOT NULL DEFAULT 'UNASSIGNED',
    project_id BIGINT,
    task_id BIGINT,
    robot_code VARCHAR(128),
    collector_id BIGINT,
    source_task_code VARCHAR(128),
    uploader_id BIGINT NOT NULL,
    metadata_status VARCHAR(16) NOT NULL DEFAULT 'READY',
    open_shared BOOLEAN NOT NULL DEFAULT FALSE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    storage_key VARCHAR(64),
    original_name VARCHAR(255),
    content_type VARCHAR(255),
    object_key VARCHAR(1024),
    source_fingerprint VARCHAR(128),
    robot_type VARCHAR(100),
    status VARCHAR(24) NOT NULL DEFAULT 'READY',
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_data_dataset_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_data_dataset_type CHECK (
        data_type IN (
            'MCAP', 'BAG', 'VIDEO', 'AUDIO', 'IMAGE', 'HDF5', 'LEROBOT',
            'MEITUAN', 'LUMOS', 'ZC0TOUCH', 'SENSEXPERIENCE', 'BVH'
        )
    ),
    CONSTRAINT ck_data_dataset_size CHECK (size_bytes >= 0),
    CONSTRAINT ck_data_dataset_duration
        CHECK (duration_seconds IS NULL OR duration_seconds >= 0),
    CONSTRAINT ck_data_dataset_annotation_status
        CHECK (annotation_status IN ('UNASSIGNED', 'ASSIGNED', 'COMPLETED')),
    CONSTRAINT ck_data_dataset_metadata
        CHECK (metadata_status IN ('PENDING', 'PROCESSING', 'READY', 'FAILED')),
    CONSTRAINT ck_data_dataset_status
        CHECK (status IN ('READY', 'PROCESSING', 'FAILED')),
    CONSTRAINT ck_data_dataset_deleted CHECK (deleted_at IS NULL OR deleted = TRUE)
);

CREATE UNIQUE INDEX uk_data_dataset_active_name
    ON data_dataset (lower(name))
    WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_data_dataset_object
    ON data_dataset (storage_key, object_key)
    WHERE storage_key IS NOT NULL AND object_key IS NOT NULL;
CREATE UNIQUE INDEX uk_data_dataset_source_active
    ON data_dataset (source_fingerprint)
    WHERE source_fingerprint IS NOT NULL AND deleted = FALSE;
CREATE INDEX idx_data_dataset_list
    ON data_dataset (deleted, annotation_status, updated_at DESC, id DESC);
CREATE INDEX idx_data_dataset_uploader
    ON data_dataset (uploader_id, id)
    WHERE deleted = FALSE;
CREATE INDEX idx_data_dataset_project
    ON data_dataset (project_id, id)
    WHERE deleted = FALSE;
CREATE INDEX idx_data_dataset_collector
    ON data_dataset (collector_id)
    WHERE deleted = FALSE;
CREATE INDEX idx_data_dataset_task
    ON data_dataset (task_id)
    WHERE deleted = FALSE;

CREATE TABLE data_dataset_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_data_dataset_tag_name UNIQUE (name),
    CONSTRAINT ck_data_dataset_tag_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE data_dataset_tag_rel (
    dataset_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (dataset_id, tag_id)
);

CREATE INDEX idx_data_dataset_tag_rel_tag
    ON data_dataset_tag_rel (tag_id);

CREATE TABLE data_annotation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id BIGINT NOT NULL,
    task_id BIGINT,
    annotator_id BIGINT,
    content_text TEXT,
    covered_duration_seconds NUMERIC(12, 3),
    is_valid BOOLEAN NOT NULL DEFAULT TRUE,
    is_qualified BOOLEAN NOT NULL DEFAULT FALSE,
    reviewed BOOLEAN NOT NULL DEFAULT FALSE,
    invalid_collect BOOLEAN NOT NULL DEFAULT FALSE,
    semantic_error BOOLEAN NOT NULL DEFAULT FALSE,
    semantic_corrected BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_data_annotation_covered
        CHECK (covered_duration_seconds IS NULL OR covered_duration_seconds >= 0)
);

CREATE INDEX idx_data_annotation_dataset ON data_annotation (dataset_id);

-- 子菜单：数据上传
CREATE TABLE data_upload_session (
    id UUID PRIMARY KEY,
    project_id BIGINT NOT NULL,
    storage_key VARCHAR(64) NOT NULL,
    data_type VARCHAR(32) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    total_size BIGINT NOT NULL,
    chunk_size INTEGER NOT NULL,
    total_chunks INTEGER NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    source_fingerprint VARCHAR(128) NOT NULL,
    robot_type VARCHAR(100),
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    uploader_id BIGINT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_data_upload_size CHECK (total_size > 0),
    CONSTRAINT ck_data_upload_chunk_size CHECK (chunk_size = 10485760),
    CONSTRAINT ck_data_upload_chunks CHECK (total_chunks > 0),
    CONSTRAINT ck_data_upload_status CHECK (
        status IN ('PENDING', 'UPLOADING', 'PAUSED', 'COMPLETING', 'SUCCESS', 'ERROR', 'CANCELLED')
    )
);

CREATE INDEX idx_data_upload_user_status
    ON data_upload_session (uploader_id, status, updated_at DESC);

CREATE TABLE data_upload_part (
    session_id UUID NOT NULL,
    part_number INTEGER NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    size_bytes BIGINT NOT NULL,
    etag VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (session_id, part_number),
    CONSTRAINT ck_data_upload_part_number CHECK (part_number >= 0),
    CONSTRAINT ck_data_upload_part_size CHECK (size_bytes > 0)
);

-- 子菜单：采集任务
CREATE TABLE data_collection_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    project_id BIGINT NOT NULL,
    target_count INTEGER NOT NULL DEFAULT 1,
    average_duration_seconds INTEGER NOT NULL DEFAULT 60,
    notes VARCHAR(2000),
    initial_scene VARCHAR(2000),
    remote_operation_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    created_by BIGINT NOT NULL,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_collection_task_name UNIQUE (name),
    CONSTRAINT ck_collection_task_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_collection_task_target_count CHECK (target_count >= 1),
    CONSTRAINT ck_collection_task_average_duration CHECK (average_duration_seconds >= 1),
    CONSTRAINT ck_collection_task_status CHECK (
        status IN ('PENDING', 'WORKING', 'REVIEW_PENDING', 'REJECTED', 'APPROVED', 'SUBMITTED')
    )
);

CREATE INDEX idx_collection_task_project_status
    ON data_collection_task (project_id, status, updated_at DESC, id DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_collection_task_creator
    ON data_collection_task (created_by, id)
    WHERE deleted_at IS NULL;

CREATE TABLE data_collection_task_assignee (
    task_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (task_id, user_id)
);

CREATE INDEX idx_collection_assignee_user
    ON data_collection_task_assignee (user_id, task_id);

CREATE TABLE data_collection_task_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    sequence_no INTEGER NOT NULL,
    action_name VARCHAR(200),
    object_name VARCHAR(200),
    target_name VARCHAR(200),
    notes VARCHAR(500),
    CONSTRAINT uk_collection_step_sequence UNIQUE (task_id, sequence_no),
    CONSTRAINT ck_collection_step_sequence CHECK (sequence_no >= 1),
    CONSTRAINT ck_collection_step_content CHECK (
        NULLIF(btrim(action_name), '') IS NOT NULL
        OR NULLIF(btrim(notes), '') IS NOT NULL
    )
);

CREATE TABLE data_collection_task_dataset (
    task_id BIGINT NOT NULL,
    dataset_id BIGINT NOT NULL,
    linked_by BIGINT,
    linked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (task_id, dataset_id)
);

CREATE INDEX idx_collection_dataset_recent
    ON data_collection_task_dataset (task_id, linked_at DESC, dataset_id DESC);

-- 子菜单：标注任务
-- 合并 V9 的快速发起字段与 V11 的完整任务工作流字段。
CREATE TABLE data_annotation_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    project_id BIGINT,
    annotator_id BIGINT,
    reviewer_id BIGINT,
    creator_id BIGINT NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    dataset_count INTEGER NOT NULL DEFAULT 0,
    rejection_reason VARCHAR(1000),
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_annotation_task_name UNIQUE (name),
    CONSTRAINT ck_annotation_task_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_annotation_task_status CHECK (
        status IN (
            'OPEN', 'COMPLETED', 'PENDING', 'WORKING', 'REVIEW_PENDING',
            'REJECTED', 'APPROVED', 'SUBMITTED'
        )
    ),
    CONSTRAINT ck_annotation_task_dataset_count CHECK (dataset_count >= 0),
    CONSTRAINT ck_annotation_task_rejection_reason
        CHECK (rejection_reason IS NULL OR char_length(rejection_reason) <= 1000)
);

CREATE INDEX idx_annotation_task_status_created
    ON data_annotation_task (status, created_at DESC, id DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_annotation_task_project
    ON data_annotation_task (project_id, created_at DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_annotation_task_people
    ON data_annotation_task (annotator_id, reviewer_id, creator_id)
    WHERE deleted_at IS NULL;

CREATE TABLE data_annotation_task_dataset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    dataset_id BIGINT NOT NULL,
    annotation_description TEXT,
    check_result VARCHAR(16),
    rejection_reason VARCHAR(1000),
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    unassigned_at TIMESTAMPTZ,
    CONSTRAINT ck_annotation_dataset_result
        CHECK (check_result IS NULL OR check_result IN ('VALID', 'INVALID')),
    CONSTRAINT ck_annotation_dataset_reason
        CHECK (rejection_reason IS NULL OR char_length(rejection_reason) <= 1000)
);

CREATE UNIQUE INDEX uk_annotation_dataset_active
    ON data_annotation_task_dataset (dataset_id)
    WHERE unassigned_at IS NULL;
CREATE INDEX idx_annotation_dataset_task
    ON data_annotation_task_dataset (task_id, assigned_at, id)
    WHERE unassigned_at IS NULL;

-- 数据质检、字典管理、分析图表、技能库、数据导出、可视化：
-- 当前没有独立数据表。
