-- 菜单：系统管理（sort_order = 20）

-- 部门管理
CREATE TABLE sys_department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(64) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_department_code UNIQUE (code),
    CONSTRAINT ck_department_not_self CHECK (parent_id IS NULL OR parent_id <> id),
    CONSTRAINT ck_department_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_department_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT ck_department_name_not_blank CHECK (btrim(name) <> '')
);

CREATE INDEX idx_department_parent_sort
    ON sys_department (parent_id, sort_order, id);

-- 用户管理
CREATE TABLE sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    email VARCHAR(254),
    phone VARCHAR(32),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    password_changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_username UNIQUE (username),
    CONSTRAINT ck_user_username_normalized CHECK (username = lower(username)),
    CONSTRAINT ck_user_username_not_blank CHECK (btrim(username) <> ''),
    CONSTRAINT ck_user_display_name_not_blank CHECK (btrim(display_name) <> ''),
    CONSTRAINT ck_user_password_hash_not_blank CHECK (btrim(password_hash) <> '')
);

CREATE UNIQUE INDEX uk_user_email_normalized
    ON sys_user (lower(email))
    WHERE email IS NOT NULL;
CREATE INDEX idx_user_department ON sys_user (department_id);
CREATE INDEX idx_user_enabled_created ON sys_user (enabled, created_at DESC);

-- 角色管理
CREATE TABLE sys_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(64) NOT NULL,
    description VARCHAR(500),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    built_in BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_role_name UNIQUE (name),
    CONSTRAINT uk_role_code UNIQUE (code),
    CONSTRAINT ck_role_code_normalized CHECK (code = upper(code)),
    CONSTRAINT ck_role_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT ck_role_name_not_blank CHECK (btrim(name) <> '')
);

CREATE INDEX idx_role_enabled ON sys_role (enabled);

-- 菜单权限
CREATE TABLE sys_menu_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    type VARCHAR(16) NOT NULL,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(100),
    path VARCHAR(255),
    component VARCHAR(255),
    icon VARCHAR(100),
    sort_order INTEGER NOT NULL DEFAULT 0,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_menu_permission_code UNIQUE (code),
    CONSTRAINT ck_menu_permission_type CHECK (type IN ('MENU', 'BUTTON')),
    CONSTRAINT ck_menu_permission_not_self CHECK (parent_id IS NULL OR parent_id <> id),
    CONSTRAINT ck_menu_permission_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_button_permission_code CHECK (type <> 'BUTTON' OR code IS NOT NULL),
    CONSTRAINT ck_menu_permission_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_menu_permission_code_not_blank CHECK (code IS NULL OR btrim(code) <> '')
);

CREATE INDEX idx_menu_permission_parent_sort
    ON sys_menu_permission (parent_id, sort_order, id);
CREATE INDEX idx_menu_permission_type_enabled
    ON sys_menu_permission (type, enabled);

-- 用户角色关系
CREATE TABLE sys_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by BIGINT,
    PRIMARY KEY (user_id, role_id)
);

CREATE INDEX idx_user_role_role ON sys_user_role (role_id, user_id);

-- 角色权限关系
CREATE TABLE sys_role_permission (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, permission_id)
);

CREATE INDEX idx_role_permission_permission
    ON sys_role_permission (permission_id, role_id);

-- 登录会话
CREATE TABLE auth_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(128) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ,
    ip_address VARCHAR(45),
    user_agent VARCHAR(512),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_auth_session_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_auth_session_expiry CHECK (expires_at > created_at),
    CONSTRAINT ck_auth_session_revocation CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX idx_auth_session_active_user
    ON auth_session (user_id, expires_at)
    WHERE revoked_at IS NULL;
CREATE INDEX idx_auth_session_expiry ON auth_session (expires_at);
