-- 菜单：文件管理（sort_order = 30）

CREATE TABLE file_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket_name VARCHAR(63) NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(255),
    size_bytes BIGINT NOT NULL,
    etag VARCHAR(128),
    uploader_id BIGINT,
    status VARCHAR(16) NOT NULL DEFAULT 'READY',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_file_object UNIQUE (bucket_name, object_key),
    CONSTRAINT ck_file_size CHECK (size_bytes >= 0),
    CONSTRAINT ck_file_status CHECK (status IN ('PENDING', 'READY', 'DELETING', 'FAILED')),
    CONSTRAINT ck_file_bucket_not_blank CHECK (btrim(bucket_name) <> ''),
    CONSTRAINT ck_file_object_key_not_blank CHECK (btrim(object_key) <> ''),
    CONSTRAINT ck_file_original_name_not_blank CHECK (btrim(original_name) <> '')
);

CREATE INDEX idx_file_uploader_created
    ON file_metadata (uploader_id, created_at DESC);
CREATE INDEX idx_file_status_created
    ON file_metadata (status, created_at DESC);
