-- 菜单：操作日志（sort_order = 40）

CREATE TABLE operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id BIGINT,
    operator_name VARCHAR(64),
    module VARCHAR(64) NOT NULL,
    action VARCHAR(64) NOT NULL,
    target_type VARCHAR(64),
    target_id VARCHAR(128),
    result VARCHAR(16) NOT NULL,
    error_summary VARCHAR(500),
    ip_address VARCHAR(45),
    user_agent VARCHAR(512),
    request_id VARCHAR(128),
    details TEXT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    duration_ms BIGINT,
    CONSTRAINT ck_operation_log_result CHECK (result IN ('SUCCESS', 'FAILURE')),
    CONSTRAINT ck_operation_log_duration CHECK (duration_ms IS NULL OR duration_ms >= 0),
    CONSTRAINT ck_operation_log_module_not_blank CHECK (btrim(module) <> ''),
    CONSTRAINT ck_operation_log_action_not_blank CHECK (btrim(action) <> '')
);

COMMENT ON COLUMN operation_log.operator_id IS
    'Historical operator identifier; intentionally not constrained so audit writes remain independent';

CREATE INDEX idx_operation_log_occurred ON operation_log (occurred_at DESC);
CREATE INDEX idx_operation_log_operator_occurred
    ON operation_log (operator_id, occurred_at DESC);
CREATE INDEX idx_operation_log_module_result_occurred
    ON operation_log (module, result, occurred_at DESC);
CREATE INDEX idx_operation_log_request_id ON operation_log (request_id);
