-- 菜单：基本配置（sort_order = 50）

-- 项目管理
CREATE TABLE basic_project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(1000),
    project_type VARCHAR(16) NOT NULL,
    access_level VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PLANNING',
    storage_provider VARCHAR(32) NOT NULL DEFAULT 'MINIO',
    storage_quota_bytes BIGINT NOT NULL,
    start_date DATE,
    end_date DATE,
    annotation_guideline TEXT,
    quality_threshold NUMERIC(5, 2) NOT NULL DEFAULT 90.00,
    review_mode VARCHAR(24) NOT NULL DEFAULT 'SINGLE_REVIEW',
    notification_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_basic_project_code UNIQUE (code),
    CONSTRAINT ck_basic_project_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT ck_basic_project_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_basic_project_type
        CHECK (project_type IN ('PERSONAL', 'TEAM', 'SHARED')),
    CONSTRAINT ck_basic_project_access
        CHECK (access_level IN ('PUBLIC', 'PRIVATE', 'RESTRICTED')),
    CONSTRAINT ck_basic_project_status
        CHECK (status IN ('PLANNING', 'ACTIVE', 'SUSPENDED', 'COMPLETED', 'ARCHIVED')),
    CONSTRAINT ck_basic_project_quota CHECK (storage_quota_bytes > 0),
    CONSTRAINT ck_basic_project_dates
        CHECK (start_date IS NULL OR end_date IS NULL OR start_date <= end_date),
    CONSTRAINT ck_basic_project_quality
        CHECK (quality_threshold >= 0 AND quality_threshold <= 100),
    CONSTRAINT ck_basic_project_review
        CHECK (review_mode IN ('NONE', 'SINGLE_REVIEW', 'DOUBLE_REVIEW'))
);

CREATE INDEX idx_basic_project_status_updated
    ON basic_project (status, updated_at DESC, id DESC);
CREATE INDEX idx_basic_project_owner ON basic_project (owner_id, id);

CREATE TABLE basic_project_member (
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(24) NOT NULL,
    data_access_level VARCHAR(16) NOT NULL DEFAULT 'READ_WRITE',
    valid_from TIMESTAMPTZ,
    valid_until TIMESTAMPTZ,
    assigned_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (project_id, user_id),
    CONSTRAINT ck_basic_project_member_role
        CHECK (role IN ('PROJECT_ADMIN', 'PROJECT_MANAGER', 'ANNOTATOR', 'REVIEWER', 'OBSERVER')),
    CONSTRAINT ck_basic_project_member_access
        CHECK (data_access_level IN ('READ_ONLY', 'READ_WRITE', 'FULL')),
    CONSTRAINT ck_basic_project_member_validity
        CHECK (valid_from IS NULL OR valid_until IS NULL OR valid_from < valid_until)
);

CREATE INDEX idx_basic_project_member_user
    ON basic_project_member (user_id, project_id);
CREATE INDEX idx_basic_project_member_validity
    ON basic_project_member (project_id, valid_from, valid_until);

-- 存储管理
CREATE TABLE cloud_storage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_key VARCHAR(64) NOT NULL,
    name VARCHAR(120) NOT NULL,
    provider VARCHAR(24) NOT NULL,
    endpoint VARCHAR(500) NOT NULL,
    region VARCHAR(100),
    bucket VARCHAR(255) NOT NULL,
    access_key_ciphertext TEXT NOT NULL,
    secret_key_ciphertext TEXT NOT NULL,
    default_storage BOOLEAN NOT NULL DEFAULT FALSE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(16) NOT NULL DEFAULT 'NEVER',
    last_check_message VARCHAR(500),
    last_check_latency_ms BIGINT,
    usage_bytes BIGINT NOT NULL DEFAULT 0,
    object_count BIGINT NOT NULL DEFAULT 0,
    last_checked_at TIMESTAMPTZ,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cloud_storage_key UNIQUE (storage_key),
    CONSTRAINT uk_cloud_storage_name UNIQUE (name),
    CONSTRAINT ck_cloud_storage_key_not_blank CHECK (btrim(storage_key) <> ''),
    CONSTRAINT ck_cloud_storage_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_cloud_storage_endpoint_not_blank CHECK (btrim(endpoint) <> ''),
    CONSTRAINT ck_cloud_storage_bucket_not_blank CHECK (btrim(bucket) <> ''),
    CONSTRAINT ck_cloud_storage_provider CHECK (
        provider IN (
            'TENCENT_COS', 'ALIYUN_OSS', 'HUAWEI_OBS', 'AWS_S3',
            'AZURE_BLOB', 'CLOUDFLARE_R2', 'MINIO'
        )
    ),
    CONSTRAINT ck_cloud_storage_status
        CHECK (status IN ('NEVER', 'AVAILABLE', 'UNAVAILABLE')),
    CONSTRAINT ck_cloud_storage_latency
        CHECK (last_check_latency_ms IS NULL OR last_check_latency_ms >= 0),
    CONSTRAINT ck_cloud_storage_usage CHECK (usage_bytes >= 0 AND object_count >= 0)
);

CREATE UNIQUE INDEX uk_cloud_storage_default
    ON cloud_storage (default_storage)
    WHERE default_storage = TRUE;
CREATE INDEX idx_cloud_storage_enabled_provider
    ON cloud_storage (enabled, provider, updated_at DESC);

-- 模型管理
CREATE TABLE ai_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacturer VARCHAR(100) NOT NULL,
    name VARCHAR(160) NOT NULL,
    access_address VARCHAR(500) NOT NULL,
    model_url VARCHAR(1000) NOT NULL,
    model_type VARCHAR(32) NOT NULL,
    access_key_ciphertext TEXT,
    secret_key_ciphertext TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_test_status VARCHAR(16) NOT NULL DEFAULT 'NEVER',
    last_test_message VARCHAR(500),
    last_test_latency_ms BIGINT,
    last_tested_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_model_manufacturer_name UNIQUE (manufacturer, name),
    CONSTRAINT ck_ai_model_manufacturer_not_blank CHECK (btrim(manufacturer) <> ''),
    CONSTRAINT ck_ai_model_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_ai_model_access_address_not_blank CHECK (btrim(access_address) <> ''),
    CONSTRAINT ck_ai_model_url_not_blank CHECK (btrim(model_url) <> ''),
    CONSTRAINT ck_ai_model_type
        CHECK (model_type IN ('CHAT', 'EMBEDDING', 'MULTIMODAL', 'RERANK', 'IMAGE', 'AUDIO')),
    CONSTRAINT ck_ai_model_test_status
        CHECK (last_test_status IN ('NEVER', 'SUCCESS', 'FAILED')),
    CONSTRAINT ck_ai_model_test_latency
        CHECK (last_test_latency_ms IS NULL OR last_test_latency_ms >= 0)
);

CREATE INDEX idx_ai_model_type_enabled
    ON ai_model (model_type, enabled, updated_at DESC);

-- Agent 管理
CREATE TABLE ai_agent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    system_prompt TEXT NOT NULL,
    model_id BIGINT NOT NULL,
    temperature NUMERIC(3, 2) NOT NULL DEFAULT 0.70,
    max_tokens INTEGER NOT NULL DEFAULT 2048,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_agent_name UNIQUE (name),
    CONSTRAINT ck_ai_agent_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_ai_agent_prompt_not_blank CHECK (btrim(system_prompt) <> ''),
    CONSTRAINT ck_ai_agent_temperature CHECK (temperature >= 0 AND temperature <= 2),
    CONSTRAINT ck_ai_agent_max_tokens CHECK (max_tokens BETWEEN 1 AND 32768)
);

CREATE INDEX idx_ai_agent_model_enabled
    ON ai_agent (model_id, enabled, updated_at DESC);
